services:
  home:
    build:
      context: ./home
    ports:
      - "80:5000"
    environment:
      - HISTORIAL_SERVICE=http://historial:5000
      - INVENTARIO_SERVICE=http://inventario:5000
      - COCINA_SERVICE=http://cocina:5000
    depends_on:
      - historial
      - inventario
      - cocina
    networks:
      - restaurant-network
    restart: unless-stopped

  historial:
    build:
      context: ./historial
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_P9LIMOSeUca2@ep-hidden-sky-ai9jg0kq-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - restaurant-network
    restart: unless-stopped

  inventario:
    build:
      context: ./inventario
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_P9LIMOSeUca2@ep-hidden-sky-ai9jg0kq-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - restaurant-network
    restart: unless-stopped

  cocina:
    build:
      context: ./cocina
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_P9LIMOSeUca2@ep-hidden-sky-ai9jg0kq-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - restaurant-network
    restart: unless-stopped

networks:
  restaurant-network:
    driver: bridge