services:
  home:
    build:
      context: ./home
    ports:
      - "80:5000"
    volumes:
      - ./restaurant.db:/app/restaurant.db
      - ./templates:/app/templates
    depends_on:
      - cocina
      - historial
      - inventario

  cocina:
    build:
      context: ./cocina

    volumes:
      - ./restaurant.db:/app/restaurant.db


  historial:
    build:
      context: ./historial

    volumes:
      - ./restaurant.db:/app/restaurant.db


  inventario:
    build:
      context: ./inventario

    volumes:
      - ./restaurant.db:/app/restaurant.db


