FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia los archivos de la aplicación al contenedor
COPY . /app

RUN mkdir -p /app/data

EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["python", "app.py"]
